/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LostRouteImport } from './routes/lost'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoundRouteImport } from './routes/found'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as EditPostPostIdRouteImport } from './routes/edit-post.$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPostPostIdRoute = EditPostPostIdRouteImport.update({
  id: '/edit-post/$postId',
  path: '/edit-post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/create-post': typeof CreatePostRoute
  '/found': typeof FoundRoute
  '/login': typeof LoginRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/edit-post/$postId': typeof EditPostPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/create-post': typeof CreatePostRoute
  '/found': typeof FoundRoute
  '/login': typeof LoginRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/edit-post/$postId': typeof EditPostPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/create-post': typeof CreatePostRoute
  '/found': typeof FoundRoute
  '/login': typeof LoginRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/edit-post/$postId': typeof EditPostPostIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/create-post'
    | '/found'
    | '/login'
    | '/lost'
    | '/map'
    | '/notifications'
    | '/saved'
    | '/signup'
    | '/edit-post/$postId'
    | '/posts/$postId'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/create-post'
    | '/found'
    | '/login'
    | '/lost'
    | '/map'
    | '/notifications'
    | '/saved'
    | '/signup'
    | '/edit-post/$postId'
    | '/posts/$postId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/create-post'
    | '/found'
    | '/login'
    | '/lost'
    | '/map'
    | '/notifications'
    | '/saved'
    | '/signup'
    | '/edit-post/$postId'
    | '/posts/$postId'
    | '/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdoptionRoute: typeof AdoptionRoute
  AiMatchRoute: typeof AiMatchRoute
  CommunityRoute: typeof CommunityRoute
  CreatePostRoute: typeof CreatePostRoute
  FoundRoute: typeof FoundRoute
  LoginRoute: typeof LoginRoute
  LostRoute: typeof LostRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  EditPostPostIdRoute: typeof EditPostPostIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-post/$postId': {
      id: '/edit-post/$postId'
      path: '/edit-post/$postId'
      fullPath: '/edit-post/$postId'
      preLoaderRoute: typeof EditPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdoptionRoute: AdoptionRoute,
  AiMatchRoute: AiMatchRoute,
  CommunityRoute: CommunityRoute,
  CreatePostRoute: CreatePostRoute,
  FoundRoute: FoundRoute,
  LoginRoute: LoginRoute,
  LostRoute: LostRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  EditPostPostIdRoute: EditPostPostIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
