/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LostRouteImport } from './routes/lost'
import { Route as FoundRouteImport } from './routes/found'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRoute
  '/ai-match': typeof AiMatchRoute
  '/community': typeof CommunityRoute
  '/found': typeof FoundRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/found'
    | '/lost'
    | '/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/found'
    | '/lost'
    | '/map'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adoption'
    | '/ai-match'
    | '/community'
    | '/found'
    | '/lost'
    | '/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdoptionRoute: typeof AdoptionRoute
  AiMatchRoute: typeof AiMatchRoute
  CommunityRoute: typeof CommunityRoute
  FoundRoute: typeof FoundRoute
  LostRoute: typeof LostRoute
  MapRoute: typeof MapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdoptionRoute: AdoptionRoute,
  AiMatchRoute: AiMatchRoute,
  CommunityRoute: CommunityRoute,
  FoundRoute: FoundRoute,
  LostRoute: LostRoute,
  MapRoute: MapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
